import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/home/Navbar/page";
import Footer from "./components/home/Footer/page";
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";
import Providers from "./providers";
import { Toaster, toast } from 'sonner';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col w-full">
        <div className="w-full lg:max-w-350 mx-auto ">
          <ClerkProvider>
            <Providers>
              <Navbar />
              <div className="py-4">
                {children}
              </div>
              <Footer />
            </Providers>
            <Toaster position="top-right" richColors /> {/* Sonner Toaster for notifications */}
          </ClerkProvider>
        </div>

      </body>
    </html>
  );
}
